language: python
jobs:
  include:
    - name: "TensorFlow 1"
      python: 3.7 
      install:
        - pip install tensorflow==1.15
    - name: "TensorFlow 2"
      python: 3.8
      install:
        - pip install tensorflow
install:
  - pip install .
script:
  - python tests.py
